- name: Install Jenkins
  hosts: jenkins
  gather_facts: false
  become: true
  tasks:
  ## INSTALL YUM
    - name: Install yum
      yum:
        name:
          - wget
          - java-1.8.0-openjdk

  ## INSTALL GIT
    - name: Install git
      yum:
        name: git
        state: present

  ## INSTALL PYTHON
    # - name: Check for Python
    #   raw: test -e /usr/bin/python
    #   changed_when: false
    #   failed_when: false
    #   register: check_python

    - name: Install Python
      raw: sudo dnf install python3
      # when: check_python.rc != 0

    - name: Install docker-py
      raw: pip3 install docker-py
      # when: check_python.rc != 0

  ## INSTALL JENKINS
    - name: Download jenkins.repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: result
      changed_when: false
      failed_when: false

    - name: Print init password Jenkins
      debug:
        var: result.stdout
      ignore_errors: yes

  ## INSTALL MAVEN

    - name: Install maven
      yum:
        name: maven
        state: latest
        
  # INSTALL DOCKER

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
 
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Add remote containerd.io package
      yum: name=https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Add user jenkins to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
      become: yes
 
    # - name: Add user <USER_SSH> to docker group
    #   user:
    #     name: <USER_SSH>
    #     groups: docker
    #     append: yes
    #   become: yes

    - name: Add user alfredobenaute to docker group
      user:
        name: alfredobenaute
        groups: docker
        append: yes
      become: yes
     
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    
    - name: Pull Maven Image
      docker_image:
        name: maven:3.6.3-jdk-8
        source: pull

    - name: Install Kubectl
      yum: 
        name: kubectl
        state: present
      

