apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: default
spec:
  selector:
    matchLabels:
      run: <APP_NAME>
  template:
    metadata:
      labels:
        run: <APP_NAME>
    spec:
      containers:
    #   - image: nginx:latest
      - image: <DOCKER_IMAGE_TAG>
        imagePullPolicy: IfNotPresent
        name: <APP_NAME>
        ports:
        - containerPort: <DOCKER_IMAGE_PORT>
          protocol: TCP